version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: archives
    formats: [binary]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"

snapshot:
  version_template: "git-{{.Commit}}"

release:
  name_template: "v{{.Version}}"

changelog:
  disable: true
